config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/auth/slack/sign-in', to: 'sessions#new'
  get '/auth/slack/callback', to: 'sessions#create'
  get '/auth/slack/sign_out', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find(session[:user_id])
  end

  def authenticate_user
    redirect_to authenticate_path if current_user.blank?
  end

  def authenticate_path
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user

  def index; end

  private

  def authenticate_path
    auth_slack_sign_in_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_or_create_by(slack_id: auth_hash.info.user_id) do |new_user|
      fill_user_info(new_user)
    end

    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def info_params
    auth_hash.info
  end

  def profile_params
    auth_hash.extra.user_info.user.profile
  end

  def fill_user_info(user)
    user.nickname = info_params.nickname
    user.name = info_params.name
    user.team_name = info_params.team
    user.team_id = info_params.team_id
    user.image_url_32 = profile_params.image_32
    user.image_url_72 = profile_params.image_72
    user.image_url_192 = profile_params.image_192
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.slim
h1
  | Home#index
div
  img src = current_user.image_url_32
  h4
    = "Hello #{current_user.name}"
  p
    = link_to "Sign out", auth_slack_sign_out_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoodShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>